baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = "Journal"
theme = "hugo-coder"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 10

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Tim"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Tim's journal"
keywords = "blog,developer,getting-things-done,personal"
info = ["Full Stack DevOps", "Maker"]
#avatarURL = "images/avatar.jpg"
gravatar = "tim@knowprocess.com"
dateFormat = "2 Jan 06"
since = 2011
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive â€“ defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/tstephen/"

[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/tstephen10/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://twitter.com/tstephen10/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/stephensontim"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 6
url = "https://myhugosite.com/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

#[[languages.en.menu.main]]
#name = "About"
#weight = 1
#url = "about/"

[[languages.en.menu.main]]
name = "Journal"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Tags"
weight = 4
url = "tags/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

[security]
[security.exec]
allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^asciidoctor$']
